flyway:
  baseline-on-migrate: true
  baseline-version: 0
  check-location: true
  locations: classpath:db/migration/h2
  sql-migration-prefix: TEST_V
  table: test_schema_version

spring:
  datasource:
    url: jdbc:h2:mem:chaps;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: true
  session:
    store-type: none


spring.cloud.stream:
  bindings:
    sink:
      consumer.concurrency: 5
      destination: sink
      group: test
    source:
      content-type: application/json
      destination: source
  rabbit.bindings:
    sink:
      consumer:
        autoBindDlq: true
        republishToDlq: true
        transacted: true
    source:
      producer:
        transacted: true

spring.redis:
  port: 6379

sample:
  cron-schedule: "0 00 20 ? * MON-FRI"
  cron-schedule-timezone: Europe/London

account-service.uri: http://localhost:8078

spring.output.ansi.enabled: ALWAYS
